server:
  port: 8090
spring:
  security:
    user:
      name: user
      password: pass
mysql:
  url: jdbc:mysql://localhost:3306/casbin?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PRC&characterEncoding=UTF8
  username: root
  password: 38941abc
  driver: com.mysql.cj.jdbc.Driver